<a href="https://colab.research.google.com/github/SyaOTing/project/blob/main/%EC%98%81%EC%96%B4%20%EB%B6%84%EC%84%9D%20%ED%85%8C%EC%8A%A4%ED%8A%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 환경 준비

In [11]:
# NLTK 세팅하기 
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

import pandas as pd

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

# 데이터 불러오기

In [8]:
# 구글 드라이브 연결을 위한 기본 세팅 
!pip install -U -q PyDrive
 
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [3]:
## 문서 ID로 실제 파일 불러오기
# 실습을 위한 역대 미국 대통령 승리 연설: George Walker Bush, Barack Obama, Donald Trump
## https://drive.google.com/file/d/1lYSlFmvCPIZ6l8_WFNHnVQI_YRlLAPgr/view?usp=sharing
#	id	person	year	text
#	1	George Walker Bush	2000	Thank you very much.\n\nGood evening, my fello...
#	2	George Walker Bush	2004	Thank you all. Thank you all for coming. We ha...
#	3	Barack Obama	2008	Hello, Chicago.\n\nIf there is anyone out ther...
#	4	Barack Obama	2012	Thank you. Thank you. Thank you so much.\n\nTo...
#	5	Donald Trump	2016	Thank you. Thank you very much, everybody. Sor...

rawdata_downloaded = drive.CreateFile({'id': '1lYSlFmvCPIZ6l8_WFNHnVQI_YRlLAPgr'})
rawdata_downloaded.GetContentFile('rawdata.csv')

In [4]:
# "rawdata.txt" 파일의 내용을 "원본데이터" 변수로 불러오기
원본데이터 = pd.read_csv('rawdata.csv')

In [5]:
#@title 기본 제목 텍스트
# "원본데이터" 변수 내용 확인하기
원본데이터

      id  year  ...                                               text Unnamed: 6
0      1  1983  ...  Hi, I’m Steve Jobs.\nIt is 1958. IBM passes up...        NaN
1      2  1997  ...  Now I’d like to talk about meaningful partners...        NaN
2      3  2001  ...  We are just getting started. I would like to t...        NaN
3      4  2005  ...  I am honored to be with you today at your comm...        NaN
4      5  2005  ...  Today we're gonna focus on the iPod mini. Now ...        NaN
..   ...   ...  ...                                                ...        ...
111  112  2005  ...  Vice President Cheney, Mr. Chief Justice, Pres...        NaN
112  113  2004  ...  THE PRESIDENT: Thank you all. (Applause.) Mr. ...        NaN
113  114  2004  ...  Well, thank you all very much for that warm we...        NaN
114  115  2004  ...  Mr. Speaker, Vice President Cheney, members of...        NaN
115  116  2004  ...  Thanks for coming, thanks for the warm welcome...        NaN

[116 rows x 7 columns]

In [51]:
# 형태소 분석
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')


저장공간  = []
for index, row in 원본데이터.iterrows():
    textdata = row[5]
    type = row[1]
    형태소 = nltk.tokenize.word_tokenize(textdata)
    형태소종합 = list(nltk.pos_tag(형태소))
    형태소종합 = pd.DataFrame.from_records(형태소종합)
    형태소종합['type'] = type
    형태소종합['count'] = 1      
    저장공간.append(형태소종합)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

TypeError: ignored

In [52]:
#@title 기본 제목 텍스트
# "형태소" 변수의 저장 내용 확인
형태소

['Today',
 'we',
 "'re",
 'gon',
 'na',
 'focus',
 'on',
 'the',
 'iPod',
 'mini',
 '.',
 'Now',
 'the',
 'iPod',
 'mini',
 'is',
 'what',
 'all',
 'of',
 'our',
 'competitors',
 'have',
 'their',
 'sights',
 'focused',
 'on',
 '.',
 'Why',
 '?',
 'Well',
 ',',
 'it',
 "'s",
 'obvious',
 '.',
 'Because',
 'the',
 'iPod',
 'mini',
 'is',
 'the',
 'most',
 'popular',
 'mp3',
 'player',
 'in',
 'the',
 'world',
 '.',
 'It',
 '’',
 's',
 'the',
 'most',
 'popular',
 'iPod',
 'and',
 'that',
 'makes',
 'it',
 'the',
 'most',
 'popular',
 'mp3',
 'player',
 'in',
 'the',
 'world',
 '.',
 'So',
 'that',
 "'s",
 'the',
 'one',
 'everybody',
 '’',
 's',
 'focused',
 'on',
 '.',
 'Well',
 ',',
 'today',
 ',',
 'we',
 "'re",
 'gon',
 'na',
 'do',
 'something',
 'pretty',
 'bold',
 '.',
 'Today',
 'we',
 "'re",
 'gon',
 'na',
 'replace',
 'it',
 '.',
 'We',
 '’',
 're',
 'gon',
 'na',
 'replace',
 'it',
 'with',
 'something',
 'new',
 '.',
 'Now',
 'let',
 "'s",
 'go',
 'back',
 'to',
 'the',
 'beginning',
 '.',
 'Because',
 'we',
 'started',
 'this',
 'all',
 'with',
 '1000',
 'songs',
 'in',
 'your',
 'pocket',
 ',',
 'right',
 '?',
 'We',
 'started',
 'it',
 'with',
 'the',
 'original',
 'iPod',
 '.',
 'And',
 'then',
 ',',
 'we',
 'carried',
 '1000',
 'songs',
 'in',
 'your',
 'pocket',
 'over',
 'to',
 'the',
 'iPod',
 'mini',
 '.',
 'Well',
 ',',
 'now',
 'we',
 "'re",
 'gon',
 'na',
 'replace',
 'the',
 'iPod',
 'mini',
 'with',
 'a',
 'new',
 'player',
 ',',
 'entirely',
 'new',
 'ground-up',
 'design',
 '.',
 'It',
 'also',
 'has',
 '1000',
 'songs',
 'in',
 'your',
 'pocket',
 '.',
 'And',
 'it',
 "'s",
 'called',
 'the',
 'iPod',
 'nano',
 '.',
 'The',
 'iPod',
 'nano',
 'is',
 'the',
 'biggest',
 'revolution',
 'since',
 'the',
 'original',
 'iPod',
 '.',
 'A',
 'lot',
 'of',
 'people',
 'have',
 'worked',
 'so',
 'hard',
 'on',
 'this',
 'over',
 'the',
 'last',
 'many',
 ',',
 'many',
 'months',
 '.',
 'And',
 'it',
 'is',
 'my',
 'privilege',
 'to',
 'show',
 'it',
 'to',
 'you',
 'now',
 '.',
 '1000',
 'songs',
 'in',
 'your',
 'pocket',
 ',',
 'the',
 'iPod',
 'nano',
 '.',
 'So',
 ',',
 'let',
 '’',
 's',
 'get',
 'a',
 'camera',
 '.',
 'I',
 '’',
 've',
 'got',
 'a',
 'pocket',
 '.',
 'Right',
 'here',
 '.',
 'Now',
 'this',
 'pocket',
 '’',
 's',
 'been',
 'the',
 'one',
 'that',
 'your',
 'iPod',
 '’',
 's',
 'going',
 'in',
 ',',
 'traditionally',
 '.',
 'The',
 'iPod',
 'and',
 'the',
 'iPod',
 'mini',
 '.',
 'Fit',
 'great',
 'in',
 'there',
 '.',
 'Ever',
 'wondered',
 'what',
 'this',
 'pocket',
 "'s",
 'for',
 '?',
 'I',
 "'ve",
 'always',
 'wondered',
 'that',
 '.',
 'Well',
 ',',
 'now',
 'we',
 'know',
 '.',
 'Because',
 'this',
 'is',
 'the',
 'new',
 'iPod',
 'nano',
 '.',
 'Alright',
 '.',
 'Let',
 '’',
 's',
 'take',
 'a',
 'closer',
 'look',
 'at',
 'it',
 '.',
 'This',
 'is',
 'the',
 'new',
 'iPod',
 'nano',
 '.',
 'It',
 'is',
 'breathtaking',
 '.',
 'You',
 'won',
 '’',
 't',
 'believe',
 'it',
 'until',
 'you',
 'hold',
 'it',
 'in',
 'your',
 'hands',
 '.',
 '1000',
 'songs',
 '.',
 'An',
 'amazing',
 'color',
 'display',
 '.',
 'A',
 'click',
 'wheel',
 '.',
 'It',
 'is',
 'one',
 'of',
 'the',
 'most',
 'amazing',
 'products',
 'Apple',
 'has',
 'ever',
 ',',
 'ever',
 'created',
 '.',
 '1000',
 'songs',
 'in',
 'your',
 'pocket',
 '.',
 'Impossibly',
 'small',
 '.',
 'It',
 '’',
 's',
 'really',
 'small',
 '.',
 'Let',
 'me',
 'show',
 'you',
 'how',
 'small',
 'this',
 'is',
 '.',
 'This',
 'thing',
 'is',
 'thinner',
 'than',
 'a',
 'number',
 '2',
 'pencil',
 '.',
 'Thinner',
 'than',
 'a',
 'number',
 '2',
 'pencil',
 '.',
 'Let',
 '’',
 's',
 'go',
 'ahead',
 'and',
 'compare',
 'it',
 'to',
 'the',
 'original',
 'iPod',
 '.',
 'This',
 'is',
 'the',
 'original',
 'iPod',
 'that',
 'also',
 'held',
 '1000',
 'songs',
 'in',
 'your',
 'pocket',
 '.',
 'Look',
 'at',
 'that',
 '.',
 'The',
 'iPod',
 'nano',
 'is',
 '80',
 '%',
 'smaller',
 'in',
 'volume',
 'than',
 'the',
 'original',
 'iPod',
 '.',
 '80',
 '%',
 'smaller',
 'means',
 'it',
 '’',
 's',
 '20',
 '%',
 'of',
 'the',
 'size',
 '.',
 'It',
 '’',
 's',
 '1/5',
 'the',
 'size',
 'of',
 'the',
 'original',
 'iPpod',
 'that',
 'we',
 'shipped',
 'less',
 'than',
 '4',
 'years',
 'ago',
 '.',
 'Ok.',
 'Let',
 '’',
 's',
 'compare',
 'it',
 'to',
 'the',
 'iPod',
 'mini',
 '.',
 'The',
 'iPod',
 'mini',
 ',',
 'an',
 'incredibly',
 'successful',
 'product',
 '.',
 'The',
 'iPod',
 'nano',
 'is',
 'half',
 'the',
 'thickness',
 ',',
 'it',
 '’',
 's',
 '62',
 '%',
 'smaller',
 'by',
 'volume',
 '.',
 'That',
 'means',
 'it',
 '’',
 's',
 'almost',
 '1/3',
 'the',
 'size',
 'of',
 'the',
 'iPod',
 'mini',
 '.',
 'Now',
 'let',
 '’',
 's',
 'take',
 'a',
 'look',
 'at',
 'some',
 'competitors',
 '.',
 'Some',
 'of',
 'their',
 'flash',
 'products',
 ',',
 'here',
 '’',
 's',
 'the',
 'Iriver',
 '.',
 'Look',
 'at',
 'this',
 '.',
 '68',
 '%',
 'smaller',
 '.',
 'It',
 '’',
 's',
 '1/3',
 'the',
 'size',
 'of',
 'a',
 'competing',
 'player',
 'that',
 'doesn',
 '’',
 't',
 'hold',
 'anywhere',
 'near',
 'the',
 'number',
 'of',
 'songs',
 '.',
 'Here',
 '’',
 's',
 'another',
 'one',
 'by',
 'a',
 'company',
 'called',
 'Creative',
 '.',
 'I',
 'thinks',
 'it',
 '’',
 's',
 'called',
 'Zen',
 'player',
 '.',
 'Again',
 ',',
 '69',
 '%',
 'smaller',
 ',',
 '1/3',
 'the',
 'size',
 '.',
 'Here',
 '’',
 's',
 'another',
 'one',
 ',',
 'I',
 'think',
 'this',
 'is',
 'Zen',
 'Neon',
 '.',
 '58',
 '%',
 'smaller',
 '.',
 'Less',
 'than',
 'half',
 'the',
 'size',
 '.',
 'Here',
 '’',
 's',
 'a',
 'player',
 'from',
 'Samsung',
 '.',
 'Again',
 ',',
 'less',
 'than',
 'half',
 'the',
 'size',
 '.',
 '59',
 '%',
 'smaller',
 '.',
 'Here',
 '’',
 's',
 'a',
 'Sony',
 'player',
 '.',
 '67',
 '%',
 'smaller',
 '.',
 'A',
 'third',
 'the',
 'size',
 '.',
 'Now',
 'let',
 'me',
 'compare',
 'to',
 'something',
 'else',
 ',',
 'which',
 'isn',
 '’',
 't',
 'a',
 'competitor',
 ',',
 'which',
 'is',
 'a',
 'really',
 'cool',
 'product',
 '.',
 'This',
 'is',
 'the',
 'coolest',
 'phone',
 'in',
 'the',
 'market',
 'till',
 'today',
 'with',
 'the',
 'iTunes',
 'phone',
 '.',
 'The',
 'Motorola',
 'RAZR',
 'phone',
 '.',
 'Right',
 '?',
 'Look',
 'at',
 'this',
 ',',
 'though',
 '.',
 '66',
 '%',
 'smaller',
 '.',
 '1/3',
 'the',
 'size',
 'of',
 'the',
 'smallest',
 'phone',
 'in',
 'the',
 'market',
 '.',
 'That',
 '’',
 's',
 'how',
 'small',
 'this',
 'is',
 '.',
 'It',
 '’',
 's',
 'really',
 'small',
 'size',
 '.',
 'But',
 ',',
 'it',
 '’',
 's',
 'got',
 'really',
 'big',
 'features',
 '.',
 'This',
 'is',
 'a',
 'full-featured',
 'iPod',
 '.',
 'So',
 ',',
 'first',
 'thing',
 'is',
 'it',
 '’',
 's',
 'got',
 'that',
 '30',
 'pin',
 'dock',
 'connector',
 'like',
 'the',
 'iPod',
 'and',
 'iPod',
 'mini',
 ',',
 'so',
 'it',
 'plugs',
 'in',
 'to',
 'the',
 'entire',
 'universe',
 'of',
 'iPod',
 'accessories',
 '.',
 'And',
 'again',
 ',',
 'a',
 'gorgeous',
 'color',
 'screen',
 '.',
 'And',
 'music',
 'is',
 'the',
 'most',
 'important',
 'thing',
 '.',
 'But',
 'we',
 '’',
 've',
 'added',
 'some',
 'other',
 'things',
 'beyond',
 'just',
 'music',
 '.',
 'We',
 '’',
 've',
 'added',
 'photos',
 'so',
 'you',
 'can',
 'have',
 'your',
 'whole',
 'photo',
 'library',
 ',',
 'up',
 'to',
 '25000',
 'photos',
 ',',
 'and',
 'the',
 'color',
 'screen',
 'is',
 'pretty',
 'nice',
 '.',
 'Very',
 'high',
 'resolution',
 '.',
 'And',
 'we',
 '’',
 've',
 'added',
 'some',
 'great',
 'things',
 'and',
 'extras',
 '.',
 'We',
 'have',
 'a',
 'new',
 'clock',
 ',',
 'which',
 'is',
 'set',
 'to',
 'Cupertino',
 'when',
 'we',
 'ship',
 ',',
 'but',
 'you',
 'can',
 'set',
 'it',
 'to',
 'any',
 'major',
 'city',
 'in',
 'the',
 'world',
 '.',
 'But',
 'you',
 'can',
 'also',
 'add',
 'as',
 'many',
 'clocks',
 'as',
 'you',
 'want',
 '.',
 'Just',
 'scroll',
 'down',
 'to',
 'see',
 'them',
 '.',
 'And',
 'they',
 'go',
 'dark',
 'when',
 'it',
 '’',
 's',
 'night',
 'time',
 '.',
 'Have',
 'many',
 'clocks',
 'you',
 'want',
 '.',
 'Of',
 'course',
 'we',
 'have',
 'games',
 '.',
 'We',
 'have',
 'beautiful',
 'calendars',
 '.',
 'We',
 'have',
 'some',
 'new',
 'things',
 ',',
 'too',
 '.',
 'We',
 'have',
 'a',
 'lap',
 'timer',
 ',',
 'a',
 'stop',
 'watch',
 'and',
 'a',
 'lap',
 'timer',
 ',',
 'so',
 'you',
 'can',
 ...]

In [53]:
# "형태소종합" 변수의 저장 내용 확인
형태소종합

          0    1  type  count
0     Today   NN  2005      1
1        we  PRP  2005      1
2       're  VBP  2005      1
3       gon  VBG  2005      1
4        na   TO  2005      1
...     ...  ...   ...    ...
1430     as   IN  2005      1
1431     we  PRP  2005      1
1432  speak  VBP  2005      1
1433  today   NN  2005      1
1434      .    .  2005      1

[1435 rows x 4 columns]

In [54]:
# "저장공간" 변수의 저장 내용 확인
저장공간

[          0    1  type  count
 0        Hi  NNP  1983      1
 1         ,    ,  1983      1
 2         I  PRP  1983      1
 3         ’  VBP  1983      1
 4         m   JJ  1983      1
 ..      ...  ...   ...    ...
 432  Orwell  NNP  1983      1
 433   right   RB  1983      1
 434   about   IN  1983      1
 435    1984   CD  1983      1
 436       ?    .  1983      1

 [437 rows x 4 columns],           0    1  type  count
 0       Now   RB  1997      1
 1         I  PRP  1997      1
 2         ’  VBP  1997      1
 3         d  NNS  1997      1
 4      like   IN  1997      1
 ...     ...  ...   ...    ...
 1459  Thank  NNP  1997      1
 1460    you  PRP  1997      1
 1461   very   RB  1997      1
 1462   much   RB  1997      1
 1463      .    .  1997      1

 [1464 rows x 4 columns],             0    1  type  count
 0          We  PRP  2001      1
 1         are  VBP  2001      1
 2        just   RB  2001      1
 3     getting  VBG  2001      1
 4     started  VBN  2001      1
 ...       ...  ...   ...    ...
 1371    where  WRB  2001      1
 1372       we  PRP  2001      1
 1373      are  VBP  2001      1
 1374    going  VBG  2001      1
 1375        .    .  2001      1

 [1376 rows x 4 columns],             0    1  type  count
 0           I  PRP  2005      1
 1          am  VBP  2005      1
 2     honored  VBN  2005      1
 3          to   TO  2005      1
 4          be   VB  2005      1
 ...       ...  ...   ...    ...
 2598      you  PRP  2005      1
 2599      all   DT  2005      1
 2600     very   RB  2005      1
 2601     much   JJ  2005      1
 2602        .    .  2005      1

 [2603 rows x 4 columns],           0    1  type  count
 0     Today   NN  2005      1
 1        we  PRP  2005      1
 2       're  VBP  2005      1
 3       gon  VBG  2005      1
 4        na   TO  2005      1
 ...     ...  ...   ...    ...
 1430     as   IN  2005      1
 1431     we  PRP  2005      1
 1432  speak  VBP  2005      1
 1433  today   NN  2005      1
 1434      .    .  2005      1

 [1435 rows x 4 columns]]

In [55]:
# "저장공간" 변수의 내용을 데이터프레임 형식으로 변환해서 "분석통합" 변수에 저장한다.
분석통합 = pd.concat(저장공간)

In [56]:
# "분석통합" 변수의 저장 내용 확인
분석통합

          0    1  type  count
0        Hi  NNP  1983      1
1         ,    ,  1983      1
2         I  PRP  1983      1
3         ’  VBP  1983      1
4         m   JJ  1983      1
...     ...  ...   ...    ...
1430     as   IN  2005      1
1431     we  PRP  2005      1
1432  speak  VBP  2005      1
1433  today   NN  2005      1
1434      .    .  2005      1

[7315 rows x 4 columns]

In [57]:
# "분석통합" 변수의 컬럼(열) 이름 변경
분석통합.columns = ["형태소", "품사", "분류", "카운트"]

In [58]:
# "분석통합" 변수의 저장 내용 확인
분석통합

        형태소   품사    분류  카운트
0        Hi  NNP  1983    1
1         ,    ,  1983    1
2         I  PRP  1983    1
3         ’  VBP  1983    1
4         m   JJ  1983    1
...     ...  ...   ...  ...
1430     as   IN  2005    1
1431     we  PRP  2005    1
1432  speak  VBP  2005    1
1433  today   NN  2005    1
1434      .    .  2005    1

[7315 rows x 4 columns]

In [59]:
# "분석통합" 변수의 내용을 형태소, 품사, 분류가 같은 것을 합치고, 카운트의 총합을 구해서 "그룹통합" 변수에 저장한다.
그룹통합 = 분석통합.groupby(['형태소', '품사', "분류"])['카운트'].sum()

In [60]:
# "그룹통합" 변수의 저장 내용 확인
그룹통합

형태소  품사   분류
!    .    2001    2
$    $    1983    4
          1997    1
          2005    3
%    NN   2001    3
                 ..
”    NNP  2005    2
     VBD  2005    1
…    CC   2001    1
     VB   1997    1
     VBZ  1997    1
Name: 카운트, Length: 2249, dtype: int64

In [61]:
# "그룹통합" 변수의 내용을 데이터프레임 형식으로 변환해서 "그룹통합" 변수에 저장한다.
그룹통합 = pd.DataFrame(그룹통합)

In [62]:
# "그룹통합" 변수의 저장 내용 확인
그룹통합

              카운트
형태소 품사  분류
!   .   2001    2
$   $   1983    4
        1997    1
        2005    3
%   NN  2001    3
...           ...
”   NNP 2005    2
    VBD 2005    1
…   CC  2001    1
    VB  1997    1
    VBZ 1997    1

[2249 rows x 1 columns]

In [63]:
# "그룹통합" 변수의 내용을 "형태소분석결과.csv" 파일로 저장한다.
# header는 컬럼(열) 정보의 포함 여부이다.
# encoding은 문자코드를 선택하는 것이다. python에서는 기본적으로 utf-8(유니코드)를 사용한다.

그룹통합.to_csv('형태소분석결과.csv', header='true', encoding='utf-8')